### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by PHHENS** [mb21/panwriter#63] opened 2021-06-16 11:35 UTC
Dear Developper,
Thanks for panwriter, which is already a great tool.

The giving procedure :
git clone git@github.com:mb21/panwriter.git
cd panwriter
yarn install

Does not work out the box : 
git clone https://github.com/mb21/panwriter --> modified URL
cd panwriter
yarn install ---> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

Can you update the procedure so that a newbie can build ;-)

**Comment by mb21** [comment] 2021-06-16 12:19
The instructions are for unix (mac or linux).. exact command might differ on windows... also make sure you have yarn installed: https://yarnpkg.com ... and if you don't want to use git on the commandline, I can recommend https://desktop.github.com

**Comment by PHHENS** [comment] 2021-06-16 12:31
I am under Debian Buster, yarn is installed through apt :
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

Thanks for your fast feedback ;-)


Le mercredi 16 juin 2021 à 05:20 -0700, Mauro Bieg a écrit :

**Comment by PHHENS** [comment] 2021-06-16 12:55
It seems that under debian the command is yarnpkg instead of yarn ...
yarnpkg install seems to work...


Le mercredi 16 juin 2021 à 05:20 -0700, Mauro Bieg a écrit :

**Comment by PHHENS** [comment] 2021-06-16 13:01
Managed to compile, and it runs into web browser.
But how to build the standalone app ?

Thanks.

Le mercredi 16 juin 2021 à 05:20 -0700, Mauro Bieg a écrit :

**Comment by PHHENS** [comment] 2021-06-16 14:18
I finally managed to build the standalone app.
Get some other questions :

- The page preview seems have a bug on
codeblocks (html pre) :
pre{ color : black; background : #f0f0f0;border-radius: 5pt 5pt; }
renders bad on page preview.

- markdown #. statement is not interpreted (autonumbering).

- How to add page numbers in a footer when exporting pdf ?

Thanks for your help.
 

Le mercredi 16 juin 2021 à 05:20 -0700, Mauro Bieg a écrit :

**Comment by mb21** [comment] 2021-06-17 07:32
> The page preview seems have a bug

Can you reproduce it with plain paged.js ? If so, it's a bug in that library PanWriter relies on....

> markdown #. statement is not interpreted (autonumbering).

I think that syntax is not in CommonMark...

> How to add page numbers in a footer when exporting pdf ?

exporting with pandoc or directly from the preview?

**Comment by PHHENS** [comment] 2021-06-17 09:54
Dear Mauro,

Le jeudi 17 juin 2021 à 00:32 -0700, Mauro Bieg a écrit :
> > The page preview seems have a bug
> Can you reproduce it with plain paged.js ? If so, it's a bug in that
> library PanWriter relies on....
Did not managed to test with paged.js, but very easy to reproduce in
panwriter :
md file :
---
header-includes: >-
<style> 
pre{ color : white; background : grey ;border-radius: 5pt 5pt; } 
</style>
---
```
zee
```
Visualize in panwriter page preview (with page breaks), the background
is black
instead of grey. 

> > markdown #. statement is not interpreted (autonumbering).
> I think that syntax is not in CommonMark...
OK, but is very convinient ;-)
> > How to add page numbers in a footer when exporting pdf ?
> exporting with pandoc or directly from the preview?
It would be nice to have it directly in the preview and of course the
same way
in exported pdf ;-)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your feedbacks

**Comment by mb21** [comment] 2021-06-20 09:40
> Did not managed to test with paged.js, but very easy to reproduce in
panwriter 

Thanks! This should be fixed with https://github.com/mb21/panwriter/commit/0981762e924b3725f76d0e6cfd7078b606223b53

---

> markdown #. statement is not interpreted (autonumbering).

You can use instead:

```
1. foo
1. bar
```

**Comment by alexmyczko** [comment] 2021-08-12 19:53
@PHHENS now when you figured building it from source, will you create a debian package? https://github.com/mb21/panwriter/issues/35

**Comment by mb21** [comment] 2021-08-15 10:11
Since building from source works, I'll close this issue...

**Closed by mb21** 2021-08-15 10:11 UTC
