### ISSUE TITLE
Failed to export error (font issue?)

### ISSUE THREAD

**Issue by joshl129** [mb21/panwriter#62] opened 2021-05-30 08:07 UTC
When I try to export a file, I get the following error message:

> Failed to export
> Called: pandoc --metadata 'mainfont=-apple-system, BlinkMacSystemFont, Segoe UI, sans serif' --metadata monobackgroundcolor=#f0f0f0 --output /home/[user name]/Documents/-[file name] --to --standalone

I experienced this issue while trying multiple files: 1) the "Install and Use Pandoc.md" file (included in the Pandoc download) and 2) a file I made that just has the word "test" in it. I also experienced this while trying to export to multiple file types (ODT and PDF). 

I'm running the latest version (0.8.0) on Ubuntu 21.04. I have Pandoc installed and just confirmed I'm able to use it via the command line (I successfully exported a markdown file to HTML).

Apologies if I'm missing something and thank you for actively developing a more user-friendly GUI for Pandoc!

**Comment by mb21** [comment] 2021-05-30 10:04
You're getting this even with a file that just contains `test`? The `--to ` part of the pandoc command you posted seems wrong: it should be `--to html`. What exactly do you select in the export dialog? Does the output filename contain the suffix `.html`?

**Comment by mb21** [comment] 2021-08-15 10:12
Closing this as I cannot reproduce. But happy to revisit if there's more info...

**Closed by mb21** 2021-08-15 10:12 UTC

**Comment by Harikar-NGO** [comment] 2021-11-10 06:29
I am facing the same problem, using appimage on linux

**Comment by mb21** [comment] 2021-11-10 08:48
Have you installed pandoc?
What exactly happens? Is there a dialog with a message? What's the message?

**Comment by Harikar-NGO** [comment] 2021-11-11 05:26
I do have pandoc installed, 

here is the error message

![image](https://user-images.githubusercontent.com/68637480/141242371-289bbb12-e2df-42c7-ba19-be9179175601.png)

here is my metadate

---
title: |
  ![](img/Harikar.png){width=0.6in} \ \ \ \ 
  \color{harikar} \fontsize{28}{12} \selectfont Vacancy Announcement
header-includes: |
  \usepackage{fancyhdr}
  \usepackage{graphicx}
  \usepackage{eso-pic}
  \usepackage{transparent}
  \usepackage{geometry}
  \usepackage{xcolor}
  \usepackage{sectsty}
  \pagestyle{fancy}
  \fancypagestyle{plain}{}
  \addtolength{\headwidth}{\linewidth}
  \fancyheadoffset{\textwidth}
  \geometry{includeheadfoot,top=0in,left=1in,right=1in,bottom=0.5in}
  \definecolor{harikar}{rgb}{0.29,0.38,0.65}
  \sectionfont{\color{harikar}}
  \subsubsectionfont{\color{harikar}}
  \fancyhf{}
  \lfoot{\includegraphics[scale=1]{img/address.png} \color{harikar} Iraq-Kurdistan – Duhok \\ \ \ \ \ Medya – Str. / Australia   }
  \cfoot{\includegraphics[scale=1]{img/unit.png} \color{harikar} HR Unit \ \ \ \ \ \ \ \ \ \ \ \ \ \includegraphics[scale=1]{img/phone.png} 0751 414 8317}
  \rfoot{\includegraphics[scale=1]{img/web.png} \color{harikar} www.harikar.org}
  \renewcommand{\headrulewidth}{0pt}
  \renewcommand{\footrulewidth}{1pt}
  \AddToShipoutPictureBG{\AtTextLowerLeft{\put(+90,+100){\transparent{0.1}\includegraphics[width=4in]{img/Harikar.png}}}}
---

**Comment by mb21** [comment] 2021-11-11 14:36
which pandoc and PanWriter versions?
also with an empty document or one with just a single word in it?

**Comment by micha06de** [comment] 2024-07-08 13:38
The problem is that by default the .html extension is missing from the file name in the export file dialog. I also had this problem. After reading https://github.com/mb21/panwriter/issues/62#issuecomment-850973800 I added .html and now it works,

**Comment by mb21** [comment] 2024-07-08 14:52
Weird, is it possible everyone having this problem is on Windows? Because I still cannot reproduce it on macOS.
If anybody wants to investigate, the code is in the [`fileExportDialog` function](https://github.com/mb21/panwriter/blob/master/electron/pandoc/export.ts#L28).

**Comment by micha06de** [comment] 2024-07-09 06:49
I have this problem under Linux.
