### ISSUE TITLE
Error with AppImage distribution and 0.6.3

### ISSUE THREAD

**Issue by kiwnix** [mb21/panwriter#15] opened 2019-05-16 17:50 UTC
When running appimage distribution in debian buster, the following error is displayed:

[26367:0516/194739.179205:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_panwrip9eVNH/chrome-sandbox is owned by root and has mode 4755.
zsh: trace trap  ./panwriter-0.6.3-x86_64.AppImage

The 0.6.2 AppImage file works.

**Comment by mb21** [comment] 2019-05-17 07:50
Thanks for the report! This seems to be caused by https://github.com/electron/electron/issues/17972

It seems there is a workaround I could apply, but not sure since I'm building on macOS... I might have time to give it a try next week (pull requests also welcome), or even better if they would fix it in the next Electron release...

**Comment by kiwnix** [comment] 2019-05-17 22:56
I agree, the user can "workarround" it enabling the userns clone for non-root users via sysctl (  sudo sysctl kernel.unprivileged_userns_clone=1 )

I tried some of the workarrounds on the electron bugreport and i was not able to fix the packaging (first time using electron and electron-builder so not surprising :smile: ), i wish it is fixed in the next electron release too.

**Comment by mb21** [comment] 2020-07-19 11:25
I just released PanWriter 0.6.5, which uses Electron 9... so this is most probably fixed now.
Let me know if not!

**Closed by mb21** 2020-07-19 11:25 UTC

**Comment by different55** [comment] 2020-12-17 05:59
Trying to run PanWriter 0.7.0 and getting bit by the same bug:

[186912:1216/235608.063896:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_PanWrigmG7YC/chrome-sandbox is owned by root and has mode 4755.

**Comment by mb21** [comment] 2020-12-17 08:03
@different55 what Linux distro/version are you on? Can you try some of the workaround [suggested in this electron issue](https://github.com/electron/electron/issues/17972#issuecomment-707723698)?

**Comment by different55** [comment] 2020-12-17 15:05
My bad, yeah. I'm on Debian Sid. Haven't tried --no-sandbox yet, but `sudo sysctl kernel.unprivileged_userns_clone=1` did work.

**Comment by mb21** [comment] 2020-12-17 15:07
Great! I didn't really find something I could implement in the code or build/release script... but let me know if you find anything...

**Comment by different55** [comment] 2020-12-17 15:34
--no-sandbox does prevent it from crashing, for some reason it also prevents it from starting properly. It just hangs with no window being created. I'm not seeing any errors out on the terminal except for the "failed to update" ones that I saw even with `kernel.unprivileged_userns_clone`
